automation:
  - id: "1643716563137"
    alias: Open Bathroom Lights on Motion Detected
    description: ""
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        motion_entity: binary_sensor.bathroom_motion_sensor
        light_target:
          area_id: bathroom
        no_motion_wait: 300
  - id: "1643716612785"
    alias: Open Toilet Lights on Motion Detected
    description: ""
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        light_target:
          area_id: toilet
        motion_entity: binary_sensor.toilet_motion_sensor
        no_motion_wait: 300
  - id: "1643716637136"
    alias: Open Storage Lights on Motion Detected
    description: ""
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        motion_entity: binary_sensor.storage_motion_sensor
        light_target:
          area_id: storage_room
        no_motion_wait: 300
  - id: "1656239974634"
    alias: Test Person
    description: ""
    trigger:
      - platform: device
        device_id: 501bd1258cfdf4016ee86e46df304e3f
        domain: nest
        type: camera_person
    condition: []
    action:
      - type: turn_on
        device_id: 79f80210f81e03d76d2b97d5eb4fd3cd
        entity_id: light.hallway_light
        domain: light
    mode: single
  - id: '1656321339197'
    alias: Test Motion
    description: ''
    trigger:
    - platform: device
      device_id: 501bd1258cfdf4016ee86e46df304e3f
      domain: nest
      type: camera_motion
    condition: []
    action:
    - type: turn_on
      device_id: 79f80210f81e03d76d2b97d5eb4fd3cd
      entity_id: light.hallway_light
      domain: light
    mode: single
